### ISSUE TITLE
Icon for Forge Sparks

### ISSUE THREAD

**Issue by rafaelmardojai** [rafaelmardojai/forge-sparks#1]
An anvil and hammer with sparks would be the first metaphor I can imagine.

![istockphoto-821663034-1024x1024](https://user-images.githubusercontent.com/6210397/220001238-a38a69be-f948-401c-bf2f-0a53f28d12f6.jpg)

**Comment by jimmac** [comment]
The whole anvil + hammer + sparks might be too complex of a metaphor.

![Forge_Sparks](https://user-images.githubusercontent.com/14821/229082817-46604b23-4399-4795-b15f-7616a556380a.png)

**Comment by jimmac** [comment]
Well maybe it could just work:

![image](https://user-images.githubusercontent.com/14821/229088614-8fa8036c-d052-4588-b761-958f970de2a4.png)

**Comment by jimmac** [comment]
While I'm enjoying the lighting effects and edge highlights, it's something that's not within the style constraints. Here's a more toned down variant:

![image](https://user-images.githubusercontent.com/14821/229107738-8065e479-6259-4657-bec1-b5744f7ceb96.png)

**Comment by rafaelmardojai** [comment]
@jimmac Thanks! Looks really nice!

Btw, sorry to bother, but currently I'm using this illustration (stolen from To Do 😅) for the empty state:

![Captura desde 2023-03-31 07-35-12](https://user-images.githubusercontent.com/6210397/229121691-79573d85-4dfb-44ca-9405-d6082415fdeb.png)

But I would like something more "forgeish", where could I request one?
