### ISSUE TITLE
[ Feature request ] Codeberg

### ISSUE THREAD

**Issue by 7system7** [rafaelmardojai/forge-sparks#25]
It would be nice to have access to the Codeberg.org's notifications. The page seems to be a modded Gitea instance, but sadly the Forge Sparks does not work w/ it. :disappointed: 

![image](https://github.com/rafaelmardojai/forge-sparks/assets/3964568/d3d2f405-3eb5-4ee5-b8d9-f15f6a22b109)

Oh, and thank you for your work. This app is awesome! :partying_face:

**Comment by rafaelmardojai** [comment]
Codeberg is a [Forgejo](https://forgejo.org/) instance and should work with that (although they use almost the same code for GitHub since they have compatible APIs).

Maybe something got broken and need fixing, I already have my Codeberg account configured and I get notifications just fine, will try  to remove it and re add it.

**Comment by rafaelmardojai** [comment]
Added it without problem :/.

That unexpected error is raised when the server returns an unexpected result when trying to get the account username, or if the server returned an unexpected http status (not `200` Success, `401` Unauthorized nor  `403` Forbidden).

**Comment by 7system7** [comment]
Thank you for your time and quick response! Somehow, for me it does not work. :cry:  I changed the instance to Forgejo but no success.

![image](https://github.com/rafaelmardojai/forge-sparks/assets/3964568/11ed8f90-b5af-4f19-b260-a081f6ae0ee1)

On the "Access tokens" list I see that, it wanted to use the key, but no success. 

![image](https://github.com/rafaelmardojai/forge-sparks/assets/3964568/7c6d4fe6-db25-4d4c-a474-354b63b601d7)

I will try tomorrow, sometimes things magically heal. :smile:

**Comment by rafaelmardojai** [comment]
If the issue persists, you can send me a temporary token privately to my email so I can debug the issue and fix it, then you can revoke the token.

**Comment by 7system7** [comment]
OK, why not, I sent it! Thank you in advance.

**Comment by rafaelmardojai** [comment]
For some reason I get the right error:

![Captura desde 2024-01-07 14-57-22](https://github.com/rafaelmardojai/forge-sparks/assets/6210397/fa8dba6a-9784-41eb-821f-4d45a6be8063)

You're missing the `read:user` scope, (you will also need `read:issue` when the app is trying to get more details like the status (open/close) of a notification subject). All the needed scopes are listed in the view.

For the next release I will try to get more info from the server to print more detailed error messages.

**Comment by 7system7** [comment]
Lol. After I added the scopes you mentioned, it started to work! Thank you! :partying_face: :champagne:
