### ISSUE TITLE
[feat] Notification tools by using Github notification_referrer_id

### ISSUE THREAD

**Issue by moritz-t-w** [rafaelmardojai/forge-sparks#26]
When you click on a notification on github.com/notifications you get this bar at the top of the target page
![image](https://github.com/rafaelmardojai/forge-sparks/assets/90388353/92e00747-8ecb-46ab-b10a-51eee9898964)
These quick actions are very handy and I'd love to get this bar when opening a notification through forge sparks.

Clicking on a notification on github adds this url param: `?notification_referrer_id=NT_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`. The process to get a valid id is probably not that hard to reverse engineer.

**Comment by rafaelmardojai** [comment]
I couldn't decipher the first part of the `NT_` format, but there's an older referrer format that stills works, so I'm using that.
