### ISSUE TITLE
Initial State Illustration.

### ISSUE THREAD

**Issue by jimmac** [rafaelmardojai/forge-sparks#3]
The current state uses a placeholder image from Todo.
![229121691-79573d85-4dfb-44ca-9405-d6082415fdeb](https://user-images.githubusercontent.com/14821/229138359-43122f65-ac38-4435-98c3-b7afd4fbb808.png)

**Comment by jimmac** [comment]
Actually the issue is twofold. The initial state actually looks like this:

![Screenshot from 2023-03-31 16-08-35](https://user-images.githubusercontent.com/14821/229143792-3056ec8a-cab2-4f92-965e-2f5490d29508.png)

So the question is if it actually need an illustration. The empty state could follwo the norm of using a  large app symbolic.

![image](https://user-images.githubusercontent.com/14821/229144079-3861f344-3c89-46fb-ad04-1be748c6614a.png)

**Comment by jimmac** [comment]
If you really desire a fullcolor illustration, something simple like this might work:

![Forge Sparks Empty](https://user-images.githubusercontent.com/14821/229144733-95ea9f5f-126e-4a37-9cda-86aa62e5d24a.png)

**Comment by rafaelmardojai** [comment]
For the initial state I was thinking on using the app icon (I just didn't had one 😅).

But for the empty state I would prefer an illustration, just to don't make it too boring :P
