### ISSUE TITLE
`Ctrl+a` keyboard shortcut overrides selecting all text in a text field

### ISSUE THREAD

**Issue by gregorni** [rafaelmardojai/forge-sparks#38]
I was editing my access tokens just now, and wanted to select all the text in the Adw.PasswordEntryRow, but using the `Ctrl+A` keyboard shortcut just opened a new Accounts window.

**Comment by rafaelmardojai** [comment]
Hmm, probably `Ctrl+A` was an unfortunate choice 😅. Any suggestions for the shortcuts?

**Comment by gregorni** [comment]
Maybe `Ctrl+Shift+A`?
