### ISSUE TITLE
Cannot build on SDK 44: libadwaita 1.3 doesn't get ToolbarView

### ISSUE THREAD

**Issue by stephanedaviet** [rafaelmardojai/forge-sparks#47]
I am trying to test my [PR](https://github.com/rafaelmardojai/forge-sparks/pull/46), but I'm not able to build the project against Gnome 44 SDK version. I got this error:

```
FAILED: src/com.mardojai.ForgeSparks.src.gresource 
/run/build/forge-sparks/src/../troll/gjspack/bin/gjspack --appid=com.mardojai.ForgeSparks --project-root /run/build/forge-sparks --resource-root /run/build/forge-sparks/src --blueprint-compiler /app/bin/blueprint-compiler --no-executable ../src/main.js --potfiles ../src/../po/POTFILES src
Gjs-Message: 15:53:33.207: JS WARNING: [resource:///gjspack/lib/lexer.asm.js 0]: Successfully compiled asm.js code (total compilation time 13ms)
error: Namespace Adw does not contain a type called Dialog
at /run/build/forge-sparks/src/widgets/accountDialog.blp line 4 column 35:
   4 |template $Gjs_AccountDialog : Adw.Dialog {
     |                                  ^
hint: Did you check your spelling?
hint: Are your dependencies up to date?
error: Namespace Adw does not contain a type called ToolbarView
at /run/build/forge-sparks/src/widgets/accountDialog.blp line 8 column 7:
   8 |  Adw.ToolbarView {
     |      ^
hint: Did you check your spelling?
hint: Are your dependencies up to date?
ninja: build stopped: subcommand failed.
Error: module forge-sparks: Child process exited with code 1
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```

`ToolbarView` has been introduced in `libadwaita` since the 1.4 version. Gnome 44 relies on [libadwaita 1.3](https://release.gnome.org/44/developers/#libadwaita).

**Comment by rafaelmardojai** [comment]
Yeah, I usually use the devel manifest `com.mardojai.ForgeSparksDevel.json`, that's why the stable one is outdated.

**Comment by stephanedaviet** [comment]
OK, but in this case, how can I test the package locally? When trying to install the one produced with the devel manifest, I got the following error:
```
$ sudo flatpak install ./forge-sparks-devel.flatpak 
error: The application com.mardojai.ForgeSparksDevel/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found
```

Note: I'm under Ubuntu 22.04, corporate laptop which isn't yet upgraded to a more recent Ubuntu (and thus Gnome) version(s).

**Comment by rafaelmardojai** [comment]
The `master` version of GNOME's flatpak runtime is available for the  `gnome-nightly` flatpak repo. Here you can find how to install that repo: https://nightly.gnome.org/.

But the commit closing this issue is updating the manifest to use the GNOME 47 stable runtime, so just rebase your changes on that (you could also edit `com.mardojai.ForgeSparks.json` and change the `runtime-version` on it).

**Comment by stephanedaviet** [comment]
Perfect. I'm not fluent with Flatpack development, learning on the way. I have tested my code and updated my PR.
